Clusters:
  c1:
    kubeconfigpath: /home/nsoffer/.config/drenv/e2e/kubeconfigs/dr1
  c2:
    kubeconfigpath: /home/nsoffer/.config/drenv/e2e/kubeconfigs/dr2
  hub:
    kubeconfigpath: /home/nsoffer/.config/drenv/e2e/kubeconfigs/hub
