#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import kubectl


def test(cluster):
    print("Deploying test vm")
    kubectl.apply("--filename=vm.yaml", context=cluster)

    print("Waiting until test vm is ready")
    kubectl.wait(
        "vm/testvm",
        "--for=condition=ready",
        "--timeout=180s",
        context=cluster,
    )

    print("Deletting test vm")
    kubectl.delete("--filename=vm.yaml", context=cluster)


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

test(cluster)
