# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

---
# yamllint disable rule:line-length
name: E2E

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Limit number of drenv workers.
  MAX_WORKERS: 4

jobs:
  e2e-rdr:
    runs-on: [self-hosted, e2e-rdr-virt]
    if: github.repository == 'nirs/ramen' && github.event.pull_request.author_association == 'OWNER'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Create virtual environment
      run: |
        hack/make-venv .venv

    - name: Delete clusters
      if: ${{ always() }}
      working-directory: test
      run: |
        source ../venv
        drenv delete envs/regional-dr.yaml

    - name: Setup libvirt
      run: test/scripts/setup-libvirt

    - name: Start clusters
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: |
          cd test
          source ../venv
          drenv start --max-workers ${{ env.MAX_WORKERS }} envs/regional-dr.yaml

    - name: Build ramen-operator container
      run: make docker-build

    - name: Deploy ramen
      run: |
        source venv
        ramenctl deploy test/envs/regional-dr.yaml

    - name: Configure ramen
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 60
        max_attempts: 3
        command: |
          source venv
          ramenctl config test/envs/regional-dr.yaml

    - name: Run e2e tests
      run: |
        cp ~/.config/drenv/rdr/config.yaml e2e/config.yaml
        make e2e-rdr

    - name: Delete clusters
      if: ${{ always() }}
      working-directory: test
      run: |
        source ../venv
        drenv delete envs/regional-dr.yaml

    - name: Cleanup drenv
      if: ${{ always() }}
      working-directory: test
      run: |
        source ../venv
        drenv cleanup -v
